--------------------------------------------------------
--  DDL for Table CASH_BACKED_CRMS_REQUEST_LOGS
--------------------------------------------------------

  CREATE TABLE "NEWIBANK"."CASH_BACKED_CRMS_REQUEST_LOGS" 
   (	"ID" NUMBER, 
	"BVN" VARCHAR2(20 BYTE), 
	"AMOUNT" VARCHAR2(256 BYTE), 
	"FEE" VARCHAR2(256 BYTE), 
	"SOURCE" VARCHAR2(20 BYTE), 
	"TENUR" VARCHAR2(20 BYTE), 
	"RATE" VARCHAR2(20 BYTE), 
	"TRANS_DATE" VARCHAR2(20 BYTE), 
	"EXPIRY_DATE" VARCHAR2(20 BYTE), 
	"BENEFICIARY_ACCOUNT" VARCHAR2(20 BYTE), 
	"BENEFICIARY_LOCATION" VARCHAR2(256 BYTE), 
	"DATE_CREATED" DATE DEFAULT SYSDATE, 
	"LAST_UPDATED" DATE, 
	"RESPONSE_CODE" VARCHAR2(20 BYTE), 
	"RESPONSE_MESSAGE" VARCHAR2(256 BYTE), 
	"RESPONSE_PAYLOAD" VARCHAR2(256 BYTE), 
	"REQUEST_BODY" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NEWIBANK_TBS" ;
--------------------------------------------------------
--  DDL for Index CASH_BACKED_LOAN_CRMS_RE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEWIBANK"."CASH_BACKED_LOAN_CRMS_RE_PK" ON "NEWIBANK"."CASH_BACKED_CRMS_REQUEST_LOGS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NEWIBANK_TBS" ;
--------------------------------------------------------
--  Constraints for Table CASH_BACKED_CRMS_REQUEST_LOGS
--------------------------------------------------------

  ALTER TABLE "NEWIBANK"."CASH_BACKED_CRMS_REQUEST_LOGS" ADD CONSTRAINT "CASH_BACKED_LOAN_CRMS_RE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NEWIBANK_TBS"  ENABLE;
  ALTER TABLE "NEWIBANK"."CASH_BACKED_CRMS_REQUEST_LOGS" MODIFY ("BVN" NOT NULL ENABLE);
  ALTER TABLE "NEWIBANK"."CASH_BACKED_CRMS_REQUEST_LOGS" MODIFY ("ID" NOT NULL ENABLE);

  
  --------------------------------------------------------
--  DDL for Table CASH_BACKLOAN_ERROR_LOG
--------------------------------------------------------

  CREATE TABLE "NEWIBANK"."CASH_BACKLOAN_ERROR_LOG" 
   (	"ERROR_DATE" VARCHAR2(20 BYTE), 
	"ERROR_MSG" VARCHAR2(2000 BYTE), 
	"ERROR_POINT" VARCHAR2(2000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NEWIBANK_TBS" ;

  
  --------------------------------------------------------
--  DDL for Table CASH_BACKLOAN_REPAYMENT_TYPES
--------------------------------------------------------

  CREATE TABLE "NEWIBANK"."CASH_BACKLOAN_REPAYMENT_TYPES" 
   (	"ID" VARCHAR2(20 BYTE), 
	"DESCRIPTIONS" VARCHAR2(200 BYTE), 
	"DEL_FLG" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NEWIBANK_TBS" ;
--------------------------------------------------------
--  DDL for Table CASH_BACKLOAN_TENOR
--------------------------------------------------------

  CREATE TABLE "NEWIBANK"."CASH_BACKLOAN_TENOR" 
   (	"ID" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"DEL_FLG" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NEWIBANK_TBS" ;

  --------------------------------------------------------
--  DDL for Table CASH_LOAN_DISBURSEMENT_REQUEST
--------------------------------------------------------

  CREATE TABLE "NEWIBANK"."CASH_LOAN_DISBURSEMENT_REQUEST" 
   (	"ID" VARCHAR2(20 BYTE), 
	"APPLICATION_NUMBER" VARCHAR2(100 BYTE), 
	"PRODUCT_CODE" VARCHAR2(20 BYTE), 
	"TENOR" VARCHAR2(20 BYTE), 
	"AMOUNT" NUMBER, 
	"ACCOUNT_NUMBER" VARCHAR2(20 BYTE), 
	"HANDLING_CHARGE" VARCHAR2(20 BYTE), 
	"INSURANCE_FEE" VARCHAR2(20 BYTE), 
	"INSURANCE_RENEWAL_FEE" VARCHAR2(20 BYTE), 
	"INTEREST_RATE" VARCHAR2(20 BYTE), 
	"CHANNEL" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"REQUEST_OBJECT" VARCHAR2(1000 BYTE), 
	"RESPONSE_OBJECT" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NEWIBANK_TBS" ;
--------------------------------------------------------
--  DDL for Index CASH_LOAN_DISBURSEMENT_REQ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEWIBANK"."CASH_LOAN_DISBURSEMENT_REQ_PK" ON "NEWIBANK"."CASH_LOAN_DISBURSEMENT_REQUEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NEWIBANK_TBS" ;
--------------------------------------------------------
--  Constraints for Table CASH_LOAN_DISBURSEMENT_REQUEST
--------------------------------------------------------

  ALTER TABLE "NEWIBANK"."CASH_LOAN_DISBURSEMENT_REQUEST" ADD CONSTRAINT "CASH_LOAN_DISBURSEMENT_REQ_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NEWIBANK_TBS"  ENABLE;
  ALTER TABLE "NEWIBANK"."CASH_LOAN_DISBURSEMENT_REQUEST" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Table CASHBACK_CREDITBUREAU
--------------------------------------------------------

  CREATE TABLE "NEWIBANK"."CASHBACK_CREDITBUREAU" 
   (	"ID" VARCHAR2(20 BYTE), 
	"USERID" VARCHAR2(20 BYTE), 
	"BUREAUIDS" VARCHAR2(20 BYTE), 
	"BVN" VARCHAR2(20 BYTE), 
	"IPADDRESS" VARCHAR2(20 BYTE), 
	"DEBITACCOUNTNO" VARCHAR2(20 BYTE), 
	"PAYMENTREFERENCE" VARCHAR2(100 BYTE), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"REQUEST_OBJECT" VARCHAR2(1000 BYTE), 
	"RESPONSE_OBJECT" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NEWIBANK_TBS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEWIBANK"."TABLE1_PK" ON "NEWIBANK"."CASHBACK_CREDITBUREAU" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NEWIBANK_TBS" ;
--------------------------------------------------------
--  Constraints for Table CASHBACK_CREDITBUREAU
--------------------------------------------------------

  ALTER TABLE "NEWIBANK"."CASHBACK_CREDITBUREAU" ADD CONSTRAINT "CASHBACK_CREDITBUREAU_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NEWIBANK_TBS"  ENABLE;
  ALTER TABLE "NEWIBANK"."CASHBACK_CREDITBUREAU" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Table CASHBACK_LOAN_REQUEST
--------------------------------------------------------

  CREATE TABLE "NEWIBANK"."CASHBACK_LOAN_REQUEST" 
   (	"ID" VARCHAR2(20 BYTE), 
	"USERID" VARCHAR2(200 BYTE), 
	"IPADDRESS" VARCHAR2(200 BYTE), 
	"ACCOUNT_NUMBER" VARCHAR2(20 BYTE), 
	"AMOUNT" VARCHAR2(2000 BYTE), 
	"TENOR" VARCHAR2(20 BYTE), 
	"RATE" VARCHAR2(200 BYTE), 
	"CHANNEL" VARCHAR2(200 BYTE), 
	"PAYMENT_REF_XDS" VARCHAR2(2000 BYTE), 
	"PAYMENT_REF_CRSERVICES" VARCHAR2(2000 BYTE), 
	"GOOD_CREDIT_STATUS_XDS" VARCHAR2(200 BYTE), 
	"DATE_GOOD_CRT_STATUS_XDS" DATE, 
	"GOOD_CREDIT_STATUS_CRSERVICES" VARCHAR2(20 BYTE), 
	"CRMS_NUMBER" VARCHAR2(200 BYTE), 
	"LOAN_ACCOUNT_NUMBER" VARCHAR2(20 BYTE), 
	"DATE_GOOD_CRT_ST_CRSERVICES" DATE, 
	"CRMS_RESPONSE_CODE" VARCHAR2(200 BYTE), 
	"CRMS_RESPONSE_MESSAGE" VARCHAR2(1000 BYTE), 
	"LOAN_RESPONSE_CODE" VARCHAR2(100 BYTE), 
	"LOAN_RESPONSE_MESSAGE" VARCHAR2(1000 BYTE), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"PRIMARY_ACCOUNT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NEWIBANK_TBS" ;
  --------------------------------------------------------
--  DDL for Table CASHBACK_LOAN_REQUEST_LOG
--------------------------------------------------------

  CREATE TABLE "NEWIBANK"."CASHBACK_LOAN_REQUEST_LOG" 
   (	"ID" VARCHAR2(20 BYTE), 
	"REQUEST_TYPE" VARCHAR2(2000 BYTE), 
	"REQUEST_OBJECT" CLOB, 
	"REQUEST_DATE" DATE DEFAULT SYSDATE, 
	"RESPONSE_OBJECT" CLOB, 
	"RESPONSE_DATE" DATE, 
	"RESPONSE_CODE" VARCHAR2(20 BYTE), 
	"REQUEST_URL" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "NEWIBANK_TBS" 
 LOB ("REQUEST_OBJECT") STORE AS BASICFILE (
  TABLESPACE "NEWIBANK_TBS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RESPONSE_OBJECT") STORE AS BASICFILE (
  TABLESPACE "NEWIBANK_TBS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;





























































--------------------------------------------------------
--  File created - Tuesday-October-27-2020   
--------------------------------------------------------
REM INSERTING into CASH_BACKLOAN_TENOR
SET DEFINE OFF;
Insert into CASH_BACKLOAN_TENOR (ID,DESCRIPTION,DEL_FLG) values ('1','One Months','N');
Insert into CASH_BACKLOAN_TENOR (ID,DESCRIPTION,DEL_FLG) values ('2','Two Months','N');
Insert into CASH_BACKLOAN_TENOR (ID,DESCRIPTION,DEL_FLG) values ('3','Three Months','N');
Insert into CASH_BACKLOAN_TENOR (ID,DESCRIPTION,DEL_FLG) values ('4','Four Months','N');
Insert into CASH_BACKLOAN_TENOR (ID,DESCRIPTION,DEL_FLG) values ('5','Five Months','N');
Insert into CASH_BACKLOAN_TENOR (ID,DESCRIPTION,DEL_FLG) values ('6','Six Months','N');
Insert into CASH_BACKLOAN_TENOR (ID,DESCRIPTION,DEL_FLG) values ('7','Seven Months','N');
Insert into CASH_BACKLOAN_TENOR (ID,DESCRIPTION,DEL_FLG) values ('8','Eight Months','N');
Insert into CASH_BACKLOAN_TENOR (ID,DESCRIPTION,DEL_FLG) values ('10','Ten Months','N');
Insert into CASH_BACKLOAN_TENOR (ID,DESCRIPTION,DEL_FLG) values ('11','Eleven Months','N');
Insert into CASH_BACKLOAN_TENOR (ID,DESCRIPTION,DEL_FLG) values ('9','Nine Months','N');
Insert into CASH_BACKLOAN_TENOR (ID,DESCRIPTION,DEL_FLG) values ('12','Twelve Months','N');


--------------------------------------------------------
--  File created - Tuesday-October-27-2020   
--------------------------------------------------------
REM INSERTING into CASH_BACKLOAN_REPAYMENT_TYPES
SET DEFINE OFF;
Insert into CASH_BACKLOAN_REPAYMENT_TYPES (ID,DESCRIPTIONS,DEL_FLG) values ('1','Monthly','N');
Insert into CASH_BACKLOAN_REPAYMENT_TYPES (ID,DESCRIPTIONS,DEL_FLG) values ('2','Quarterly','N');
Insert into CASH_BACKLOAN_REPAYMENT_TYPES (ID,DESCRIPTIONS,DEL_FLG) values ('3','Biannual','N');
Insert into CASH_BACKLOAN_REPAYMENT_TYPES (ID,DESCRIPTIONS,DEL_FLG) values ('4','Bulk repayment at the end of the tenure','N');
