--------------------------------------------------------
--  File created - Sunday-November-01-2020   
--------------------------------------------------------
REM INSERTING into CHANNEL_GL_ACCOUNTS
SET DEFINE OFF;
Insert into CHANNEL_GL_ACCOUNTS (MODULE_ID,GL_ACCOUNT,DEL_FLG,CREATED_DATE,CREATED_BY) values ('CIBMAKER','250940079','N',to_date('18-FEB-20','DD-MON-RR'),'SYSTEM');
Insert into CHANNEL_GL_ACCOUNTS (MODULE_ID,GL_ACCOUNT,DEL_FLG,CREATED_DATE,CREATED_BY) values ('WALLET','250920001','N',to_date('18-FEB-20','DD-MON-RR'),'SYSTEM');
Insert into CHANNEL_GL_ACCOUNTS (MODULE_ID,GL_ACCOUNT,DEL_FLG,CREATED_DATE,CREATED_BY) values ('OMNIFLOW','250920001','N',to_date('18-FEB-20','DD-MON-RR'),'SYSTEM');
Insert into CHANNEL_GL_ACCOUNTS (MODULE_ID,GL_ACCOUNT,DEL_FLG,CREATED_DATE,CREATED_BY) values ('OMNIFLOW','160680117','N',to_date('18-FEB-20','DD-MON-RR'),'SYSTEM');
Insert into CHANNEL_GL_ACCOUNTS (MODULE_ID,GL_ACCOUNT,DEL_FLG,CREATED_DATE,CREATED_BY) values ('UNION_ONE','250920001','N',to_date('18-FEB-20','DD-MON-RR'),'SYSTEM');
Insert into CHANNEL_GL_ACCOUNTS (MODULE_ID,GL_ACCOUNT,DEL_FLG,CREATED_DATE,CREATED_BY) values ('PMARCUS','250990140','N',to_date('18-FEB-20','DD-MON-RR'),'SYSTEM');
Insert into CHANNEL_GL_ACCOUNTS (MODULE_ID,GL_ACCOUNT,DEL_FLG,CREATED_DATE,CREATED_BY) values ('OMNIFLOW','250940079','N',to_date('18-FEB-20','DD-MON-RR'),'SYSTEM');
Insert into CHANNEL_GL_ACCOUNTS (MODULE_ID,GL_ACCOUNT,DEL_FLG,CREATED_DATE,CREATED_BY) values ('APPZONE','160680010','N',to_date('17-JUL-20','DD-MON-RR'),'SYSTEM');
Insert into CHANNEL_GL_ACCOUNTS (MODULE_ID,GL_ACCOUNT,DEL_FLG,CREATED_DATE,CREATED_BY) values ('APPZONE','420996021','N',to_date('17-JUL-20','DD-MON-RR'),'SYSTEM');
