create or replace PACKAGE UBN_EMAILOTP_PKG
IS
  
  
  FUNCTION saveemailotprequest(
      p_ACCOUNT_NUMBER IN VARCHAR2,
      p_AMOUNT         IN VARCHAR2,
       p_CUSTOMER_NUMBER      IN VARCHAR2,
      p_CHANNEL        IN VARCHAR2,
      p_REQUEST_OBJECT IN VARCHAR2 ,
      p_REQUEST_TYPE IN VARCHAR2)
    RETURN VARCHAR2;
  FUNCTION update_email_otp_request(
      p_ID              IN VARCHAR2,
      p_RESPONSE_OBJECT IN VARCHAR2)
    RETURN VARCHAR2 ;
    
    FUNCTION update_emailotp_gen_values
    (
      p_ID              IN VARCHAR2,
      p_RESP_CODE            IN VARCHAR2
    )
    RETURN VARCHAR2;
 PROCEDURE FETCH_RECORD(
    c_result OUT SYS_REFCURSOR,
    P_RESP_CODE OUT VARCHAR2,
    P_RESP_MESSAGE OUT VARCHAR2);
    
    
     FUNCTION F_DECRYPT (p_input VARCHAR2)
   RETURN VARCHAR2;
   
  FUNCTION VALIDATE_OTP(PCUSTOMERNUMBER IN VARCHAR2,
                        PACCOUNTNUMBER  IN VARCHAR2,
                        POTP            IN VARCHAR2) RETURN VARCHAR2;
                        
                        FUNCTION VALIDATE_OTP_REQUEST(
      p_ACCOUNT_NUMBER IN VARCHAR2,
      p_AMOUNT         IN VARCHAR2,
      p_CUSTOMER_NUMBER      IN VARCHAR2,
      p_CHANNEL        IN VARCHAR2,
      p_REQUEST_OBJECT IN VARCHAR2 ,
      p_REQUEST_TYPE IN VARCHAR2)
    RETURN VARCHAR2;
   
  FUNCTION addOtpChannel(
    P_CUSTOMER_NUMBER IN VARCHAR2,
    P_ACCOUNT_NUMBER  IN VARCHAR2,
    P_OTP_CHANNEL_ID  IN VARCHAR2,
    P_CREATED_BY      IN VARCHAR2,
    P_INDEMNITY_FLAG  IN VARCHAR2
  )
    RETURN VARCHAR2;
  FUNCTION updateOtpChannel(
    P_ACCOUNT_NUMBER  IN VARCHAR2,
    P_ACTIVE_STATUS   IN VARCHAR2,
    P_OTP_CHANNEL_ID  IN VARCHAR2,
    P_UPDATED_BY      IN VARCHAR2
  )
    RETURN VARCHAR2;
  FUNCTION checkCustomerSubscription(
    P_CUSTOMER_NUMBER IN VARCHAR2
    )
    RETURN VARCHAR2;
END UBN_EMAILOTP_PKG;